### ISSUE TITLE
Position.scores() can cause the JVM to crash.

### ISSUE THREAD

**Issue by MrSampson** [ngocdaothanh/JStockfish#1]
I accidentally called the Position.scores() method without the "startpos moves" command and the JVM crashed! :-D

> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x00007fc540421377, pid=13185, tid=140484629186304
> #
> # JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 compressed oops)
> # Problematic frame:
> # C  [libjstockfish.so+0x14377]  Material::probe(Position const&)+0x37
> #
> # Core dump written. Default location: /home/sampson/core or core.13185
> #
> # An error report file with more information is saved as:
> # /home/sampson/hs_err_pid13185.log
> #
> # If you would like to submit a bug report, please visit:
> #   http://bugreport.java.com/bugreport/crash.jsp
> # The crash happened outside the Java Virtual Machine in native code.
> # See problematic frame for where to report the bug.
> #

I realize this isn't really a JStockfish issue, but I guess some sort of error checking would be reasonable? Having the JVM crash is, generally, bad.

**Comment by ngocdaothanh** [comment]
Stockfish itself is not robust with invalid input.

If you look at its [issues page](https://github.com/official-stockfish/Stockfish/issues?q=is%3Aissue), you can see many issues that people report Stockfish has bug, but it turns out that people gave them garbage and it gave back garbage or crashed.

Example:
https://github.com/official-stockfish/Stockfish/issues/1014
